apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    namespace "com.thelinkphone.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.thelinkphone.app"
        minSdk 24
        targetSdk 35
        versionCode 10400
        versionName "1.4.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile(
                    "proguard-android-optimize.txt"
            ), "proguard-rules.pro"
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = false
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.github.bumptech.glide:glide:4.15.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.github.aitsuki:SwipeMenuRecyclerView:2.1.5'
    implementation 'com.makeramen:roundedimageview:2.3.0'
    implementation 'com.romainpiel.shimmer:library:1.4.0'
    implementation 'com.github.yalantis:ucrop:2.2.8'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.github.yuriy-budiyev:code-scanner:2.3.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    implementation 'com.github.chtgupta:QRUtils-Android:0.1.0'

    implementation platform('com.google.firebase:firebase-bom:32.7.0')
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-analytics'
    // Add Kotlin stdlib with compatible version
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.7.1"

    //RevenueCat
    implementation 'com.revenuecat.purchases:purchases:9.15.2'
    implementation 'com.revenuecat.purchases:purchases-ui:9.15.2'

    // CameraX (Bill Capture)
    def camerax_version = "1.5.1"

    // Required for ProcessCameraProvider future handling
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
    implementation "androidx.camera:camera-view:$camerax_version"
    implementation "androidx.camera:camera-extensions:$camerax_version"

    implementation "com.google.guava:guava:31.1-android"
    implementation 'com.airbnb.android:lottie:6.4.0'
}
